version: '3'

services:
  frontend:
    image: xapsiel3301/mtaste_frontend
    container_name: 'frontend'
    ports:
      - "8083:80"
    networks:
      - back_net
    depends_on:
      - backend

  backend:
    image: xapsiel3301/mtaste_backend
    container_name: 'backend'  # Удалите пробел здесь
    ports:
      - "8082:8082"
    networks:
      - back_net
  mongodb:
    image: 'xapsiel3301/mtaste_mongodb'
    container_name: 'mongodb'
    networks:
      - back_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '27017:27017'
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=10

networks:
  back_net:
    driver: host