services:

  backend:
    image: 'xapsiel3301/mtaste_backend'
    container_name: 'backend'
    ports:
      - '8084:8082'
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - back_net
  mongodb:
    image: 'xapsiel3301/mtaste_mongodb'
    container_name: 'mongodb'
    networks:
      - back_net
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
    ports:
      - '8083:27017'
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=30

networks:
  back_net: